# Generated by Django 5.0.6 on 2024-05-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodeguero',
            name='nro_cel_bod',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nro_cel',
        ),
        migrations.RemoveField(
            model_name='contador',
            name='nro_cel_cont',
        ),
    ]
